server:
  port: 8010 # 服务端口
spring:
  application:
    name: userService # 服务名称，在euraka和nacos中展示
  datasource: #因为父项目中已经配置了mybatis，这里不配置就会报错
    url: jdbc:mysql://localhost:3306/spring001?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    dynamic:
      primary: ds0
      strict: false
      datasource:
        ds0:
          url: jdbc:mysql://localhost:3306/spring001?useSSL=false
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
        cluster-name: SH # 集群名称
mybatis-plus: # mybatis-plus配置
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名
logging:
  level:
    root: info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka
#      config:
#        import=nacos: 192.168.3.145:8848
#          nacos: application.yml # nacos配置中心地址
#        import-check:
#          enabled: false # 是否开启配置中心检查
#        group: DEFAULT_GROUP # nacos配置中心组
#        file-extension: yml # nacos配置中心文件类型
#        namespace: dev # nacos配置中心命名空间
#========================================================
#要将服务注册到eureka上，需要在application.yml中添加以下内容：
#注册之前，需要在pom中引入客户端依赖
#eureka:
#  client:
#    service-url: # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
#========================================================
#pattern:
#  name: 本地环境local
#========================================================
#  shardingsphere:
#    sharding:
#      default-database-strategy:
#      tables:
#========================================================
