server:
  port: 8002
#如果不配置数据库连接，就会报错：
#  dynamic-datasource initial loaded [0] datasource,Please add your primary datasource or check your configuration
spring:
  application:
    name: feignApi
  datasource: # 因为父项目中已经配置了mybatis，这里不配置就会报错
    url: jdbc:mysql://localhost:3306/spring001?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000 #feign客户端超时时间
            read-timeout: 5000 #feign客户端超时时间
            logger-level: basic #日志级别
      httpclient:
        enabled: true #禁用httpclient
        max-connections: 200 #连接池最大连接数，默认为500
        max-connections-per-route: 50 #单个主机的最大连接数，默认为50


# 为什么不用配置nacos注册地址：
#  如果您是将OpenFeign客户端独立出一个模块,且这个模块只是用于发起远程调用,不提供服务,则它不需要注册到Nacos中。
#  注册到Nacos的主要是服务提供方,以便服务消费方可以发现并调用它。
#  对于OpenFeign客户端模块,
#  它仅充当一个声明式的HTTP客户端。你只需要在服务消费方应用中引入这个OpenFeign模块，并使用它调用其他服务即可。
